spring:
  application:
    name: e-commerce-api
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /api/v1


