
CREATE TABLE products (
                          id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          name VARCHAR2(255) NOT NULL,
                          description VARCHAR2(1000),
                          price NUMBER(10, 2),
                          stock_quantity NUMBER(10) DEFAULT 0 NOT NULL,
                          image_url VARCHAR2(500),
                          active NUMBER(1) DEFAULT 1 NOT NULL,
                          category_id NUMBER(19) NOT NULL,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          created_by VARCHAR2(255),
                          updated_by VARCHAR2(255),
                          CONSTRAINT fk_products_category
                              FOREIGN KEY (category_id)
                                  REFERENCES categories (id)
);